### ISSUE TITLE
外卖小哥车祸去世

### ISSUE THREAD

**Issue by weilueluo** [R-r-riddikulus/riddikulus-shanghai-2022#59]
（转自微博用户[@superpuer](https://weibo.com/2454762903/LpGrLcSWJ)）

一直以来被封在家，今天切实体会了上海医疗的瘫痪。就在刚刚，外卖小哥发生车祸，头部受伤，一地的血，距离拨打120已经1个小时了，120没来，警察来了，家属来了，120依旧没来…

![9250b597ly1h1iyy9netwj20ko0dh76t](https://user-images.githubusercontent.com/39546701/164777426-bb27585c-3acd-4556-b44e-33d65ae0b2da.jpg)

**Comment by bihaiqiyuan** [comment]
靠，刚刚在微博上刷到这条，确定去世了？

**Comment by Redcxx** [comment]
> 靠，刚刚在微博上刷到这条，确定去世了？

据[博主的说法](https://weibo.com/2454762903/LpGwCjcXh)，是的。
